# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-07 11:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0041_issue_short_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submission', '0052_auto_20210525_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalReportReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalReportRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.ForeignKey(help_text='The journal that the user will receive the report for', on_delete=django.db.models.deletion.CASCADE, to='journal.Journal')),
                ('user', models.ForeignKey(help_text='The user who will receive the report', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JournalReportStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField()),
                ('downloads', models.PositiveIntegerField()),
                ('citations', models.PositiveIntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.Article')),
            ],
        ),
        migrations.AddField(
            model_name='journalreportreceipt',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.JournalReportRecipient'),
        ),
    ]
